services:
  caddy:
    container_name: caddy
    image: caddy:2-alpine
    restart: unless-stopped
    environment:
      SITE_ADDRESS: ${SITE_ADDRESS:-localhost}
    networks:
      - guyc-at
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  guyc-at:
    name: guyc-at
