networks:
  guyc-at:
    name: guyc-at
services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    container_name: caddy
    working_dir: /etc/caddy
    environment:
      SITE_ADDRESS: ${SITE_ADDRESS:-localhost}
    networks:
      - guyc-at
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./server:/etc/caddy
      - ./site/public:/srv
    command:
      - caddy
      - run
